remote_theme: cotes2020/jekyll-theme-chirpy

title: Dream Team
tagline: Welcome to the Dream Team project!
description: >-
  A minimal, responsive, and feature-rich Jekyll theme for technical writing.

url: "https://tensiondriven.github.io"
baseurl: "/dream-team"

lang: en

timezone: America/New_York

github:
  username: tensiondriven

social:
  name: Dream Team
  links:
    - https://github.com/tensiondriven/dream-team

theme_mode: dual

toc: true

comments:
  active: false

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache