title: Dream Team
tagline: Welcome to the Dream Team project!
description: >-
  A minimal, responsive, and feature-rich Jekyll theme for technical writing.

url: "https://tensiondriven.github.io"
baseurl: "/dream-team"

lang: en

timezone: America/New_York

github:
  username: tensiondriven

social:
  name: Dream Team
  links:
    - https://github.com/tensiondriven/dream-team

toc: true

paginate: 10

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap